# el docker file es un paso a paso de lo que deberia hacer mi imagen para que funcione en cualquier sistema

from nginx: latest #se especidica la imagen base a usar
WORKDIR /usr/share/html

copy . .  #copia los archivos de tu ruta actual dentro del contenedor
